user_token: ZGQxMWJlMzUtOTc0My00NDMyLTllOWEtODhhZjdlNDliYzA4XzMyNDY

session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=
admin:
  email: admin@admin.com
  password: admin
bot:
  token: vk1.a.6cgikVdpqfHnhwQlOyaFcSQGbCYkIPK9W1nzpTQSV-G_OvYJLicQ5jX1NsIYbP2ZEvyYZ77IZuMatfRGgjD9lnKY4OsWjzFZAqr5VHxpaUbfbeJ0bEQMl90m2jlbVUk8nCDgQQBxxYH3m1GXKlD7ehLo-mKcGSSf68COyox74xgqYEYDA7L9SUteTbhhF_si
  group_id: 214891743


