user_token: ZGQxMWJlMzUtOTc0My00NDMyLTllOWEtODhhZjdlNDliYzA4XzMyNDY=

session:
  key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=
admin:
  email: admin@admin.com
  password: admin
bot:
  token: token
  group_id: 1


